### PR TITLE
Allow for namespaces to be expanded and collapsed

### PR DESCRIPTION
**Pull request by skendrot**
Use the details and summary elements to allow for namespaces to be expanded and collapsed

Note: This is not supported on all browsers: https://caniuse.com/#feat=details

UPDATE: No longer uses the details and summary elements. Now uses CSS/JS to accomplish expand/collaspe

### CODE REVIEW

**Comment by skendrot** [comment]
Here's what this looks like in IE11 (without bringing in libraries like [modernizr](https://modernizr.com)

image

**Comment by skendrot** [comment]
Appears that bringing in modernizr doesn't even help IE11

**Comment by Odonno** [comment]
I think it is a counter-proposition but you may need a complete CSS library for this, like bootstrap. There is plenty of great stuff.

**Comment by skendrot** [comment]
You don't need an entire library for collapsing panels. It's easy enough to implement with minimal css/js. I went this route because all moden browsers already support it with no extra css/js

**Comment by skendrot** [comment]
I'm happy to adjust the approach and not use the details and summary elements

**Comment by dotMorten** [comment]
Edge doesn't support it either according to that link. What happens there?
Also does it start out collapsed? Is there a way to collapse/uncollapse all? Personally I prefer the big picture and not having to uncollapse each section one by one.

**Comment by dotMorten** [comment]
@Odonno For now I'd prefer keeping the generated output single-file and not bring in a bunch of dependencies.

**Comment by skendrot** [comment]
Did not see that Edge doesn't support it. Looks like crap there also. 
The default is to collapse, but with open tag, sections are open. I'll do another commit to remove details/summary and do it with a little CSS/js magic

**Pull request merged**
